### ISSUE TITLE
Path to bookmarks

### ISSUE THREAD

**Issue by Ypot** [JacopoBucchioni/vlc-permanents-bookmarks#1]
Hi
Where are the bookmarks saved? 
Thanks for this extension :-)

**Comment by JacopoBucchioni** [comment]
Hi Thanks,
the bookmarks are saved in the user's vlc data directory under `/lua/extensions/userdata/bookmarks`
For Windows the whole path is `%APPDATA%\vlc\lua\extensions\userdata\bookmarks`
while for linux and mac should be `~/.local/share/vlc/lua/extensions/userdata/bookmarks` `/Users/user_name/Library/Application\ Support/org.videolan.vlc/lua/extensions/userdata/bookmarks` respectively (where `user_name` is your username)
If you use a linux or mac system let me know if that is correct
