### ISSUE TITLE
[Suggestion] Replace the vanilla bookmarks

### ISSUE THREAD

**Issue by caffeineLover** [JacopoBucchioni/vlc-permanents-bookmarks#5]
Can this replace the vanilla VLC Bookmarks?  It would be nice to access this bookmark manager with control-b instead of the menu system.  Especially since this makes the vanilla bookmark system ridiculously useless.

**Comment by JacopoBucchioni** [comment]
Unfortunately at the moment vlc doesn't allow to assign keyboard shortcuts for opening extensions. The closest thing you can do is prees alt + i to open the View menu and scroll down to the extension with the keys.
If you are in mac OS another possible solution is explained here: https://forum.videolan.org/viewtopic.php?t=78902#p450085

**Comment by caffeineLover** [comment]
That is truly unfortunate!  I sincerely hope somebody has filed a feature request against VLC, since the whole point of an extension is increasing the usability and feature set of the program.  Not being able to assign a shortcut sort of misses the whole point!

Anyway, here is an autohotkey script that opens your bookmarks-on-steroids on control-b instead of the lame default bookmark manager.   The only thing that may need to be tweaked is the number of times you have to press the down arrow key to reach the "Bookmarks" item of the View menu.  On my system, I have to press it 9 times.  Changing my script is trivial.

```
#SingleInstance Force

#IfWinActive ahk_exe vlc.exe
^b::
	Send !i{DOWN 9}{ENTER}
	return
```
