### ISSUE TITLE
[Suggestion] Implement keyboard shortcut to cycle through bookmarks

### ISSUE THREAD

**Issue by parikramatic** [JacopoBucchioni/vlc-permanents-bookmarks#6]
Great extension, has already saved me a ton of time. and the hash logic is a lifesaver when moving the same files around.

It would be great to be able to advance to the next bookmark by pressing a key, similar to the built-in bookmarks manager.

**Comment by JacopoBucchioni** [comment]
Unfortunately vlc does not allow to assign hotkeys to third-party extensions.
As mentioned here https://github.com/JacopoBucchioni/vlc-permanents-bookmarks/issues/5 the closest thing you can do to have a similar feature is to use the vlc built-in shortcuts to open the view menu and scroll down to the extension
